import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { newDb } from "pg-mem";
import { translateSql } from "../server/db/postgres-sync.js";
import { connectionConfig } from "../server/db/connection-config.js";
import { migrate as policySchema } from "../server/modules/policy/schema.js";
import { migrate as trainingSchema } from "../server/modules/training/schema.js";
import { seedPolicies, seedPolicyDemoActivity } from "../server/modules/policy/seed.js";
import { seedCourses, seedDemoActivity } from "../server/modules/training/seed.js";
import { createStore as createPolicyStore } from "../server/modules/policy/store.js";
import { createStore as createTrainingStore } from "../server/modules/training/store.js";
import { createMatrix } from "../server/modules/training/matrix.js";

test("PostgreSQL adapter converts SQLite placeholders and conflict handling", () => {
  assert.equal(
    translateSql("INSERT OR IGNORE INTO users (username) VALUES (?)", { returning: true }),
    "INSERT INTO users (username) VALUES ($1) ON CONFLICT DO NOTHING RETURNING id"
  );
  assert.equal(
    translateSql("SELECT '?' AS literal, id FROM users WHERE username = ? AND id = ?"),
    "SELECT '?' AS literal, id FROM users WHERE username = $1 AND id = $2"
  );
  assert.equal(
    translateSql("SELECT * FROM users WHERE (? IS NULL OR department = ?)"),
    "SELECT * FROM users WHERE (CAST($1 AS TEXT) IS NULL OR department = $2)"
  );
});

test("Supabase TLS is encrypted for demos and certificate-verified when a CA is configured", () => {
  const DATABASE_URL = "postgresql://postgres.project:example%23pass@pooler.example.com:6543/postgres?sslmode=require";
  const demo = connectionConfig({ DATABASE_URL, SECUREAWARE_DEMO_DATA: "on" });
  assert.equal(demo.port, 6543);
  assert.equal(demo.password, "example#pass");
  assert.deepEqual(demo.ssl, { rejectUnauthorized: false });
  const verified = connectionConfig({ DATABASE_URL, SUPABASE_DB_CA_CERT: "-----BEGIN CERTIFICATE-----\\nexample\\n-----END CERTIFICATE-----" });
  assert.equal(verified.ssl.rejectUnauthorized, true);
  assert.match(verified.ssl.ca, /\nexample\n/);
  assert.throws(() => connectionConfig({ DATABASE_URL }), /SUPABASE_DB_CA_CERT/);
});

test("PostgreSQL adapter converts JSON array searches", () => {
  const sql = translateSql("SELECT DISTINCT j.value AS id FROM quiz_attempts a, json_each(a.question_ids) j WHERE a.user_id = ?");
  assert.match(sql, /j\.value::integer AS id/);
  assert.match(sql, /jsonb_array_elements_text\(a\.question_ids::jsonb\) AS j\(value\)/);
  assert.match(sql, /a\.user_id = \$1/);
});

test("policy and training schemas become identity-backed and private to API roles", () => {
  const sources = [];
  policySchema({ exec: (sql) => sources.push(sql) });
  trainingSchema({ exec: (sql) => sources.push(sql) });
  for (const source of sources) {
    const sql = translateSql(source, { schema: true });
    assert.match(sql, /GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
    assert.doesNotMatch(sql, /\bGLOB\b|\bIFNULL\b/);
    assert.match(sql, /ENABLE ROW LEVEL SECURITY/);
    assert.match(sql, /REVOKE ALL ON \w+ FROM anon, authenticated/);
  }
});

test("translated feature schemas parse as PostgreSQL", () => {
  // pg-mem does not implement RLS/GRANT or the regex operator in CHECK; those
  // statements are inspected above and the remaining DDL is executed here.
  const postgres = newDb();
  postgres.public.none("CREATE TABLE users (id INTEGER PRIMARY KEY)");
  for (const migrate of [policySchema, trainingSchema]) {
    migrate({ exec(source) {
      const sql = translateSql(source, { schema: true })
        .replaceAll(/ALTER TABLE [a-z_]+ ENABLE ROW LEVEL SECURITY; REVOKE ALL ON [a-z_]+ FROM anon, authenticated;/g, "")
        .replace(/CHECK\(version_label ~ [^)]+\)/g, "");
      postgres.public.none(sql);
    } });
  }
  assert.ok(postgres.public.getTable("policies"));
  assert.ok(postgres.public.getTable("training_courses"));
});

test("translated seeds create policies and courses in a PostgreSQL-like database", () => {
  const postgres = newDb();
  const source = fs.readFileSync(new URL("../server/index.js", import.meta.url), "utf8");
  const foundationSchema = source.match(/db\.exec\(`([\s\S]*?)`\);/)?.[1];
  assert.ok(foundationSchema);
  const withoutApiGrants = (sql) => sql
    .replaceAll(/ALTER TABLE [a-z_]+ ENABLE ROW LEVEL SECURITY; REVOKE ALL ON [a-z_]+ FROM anon, authenticated;/g, "")
    .replace(/CHECK\(version_label ~ [^)]+\)/g, "");
  postgres.public.none(withoutApiGrants(translateSql(foundationSchema, { schema: true })));
  for (const migrate of [policySchema, trainingSchema]) {
    migrate({ exec: (sql) => postgres.public.none(withoutApiGrants(translateSql(sql, { schema: true }))) });
  }
  for (const [username, role] of [
    ["security.admin", "Security/HR Admin"], ["system.admin", "System Admin"],
    ["manager.demo", "Department Manager"], ["manager.consulting", "Department Manager"],
    ["employee.demo", "Employee"], ["consultant.demo", "Employee"], ["dev.demo", "Employee"]
  ]) {
    postgres.public.none(`INSERT INTO users (username,display_name,role,department,password_salt,password_hash,created_at)
      VALUES ('${username}','${username}','${role}','IT','test','test','2026-01-01')`);
  }
  const literal = (value) => value == null ? "NULL" : typeof value === "number" ? String(value) : `'${String(value).replaceAll("'", "''")}'`;
  const db = {
    exec(sql) { if (!/^(BEGIN|COMMIT|ROLLBACK)/i.test(sql)) postgres.public.none(withoutApiGrants(translateSql(sql, { schema: true }))); },
    prepare(sourceSql) {
      const translated = translateSql(sourceSql, { returning: true });
      const query = (values) => postgres.public.query(translated.replace(/\$(\d+)/g, (_, index) => literal(values[Number(index) - 1])));
      return {
        get: (...values) => query(values).rows[0],
        all: (...values) => query(values).rows,
        run: (...values) => {
          const result = query(values);
          return { changes: result.rowCount, lastInsertRowid: result.rows[0]?.id ?? 0 };
        }
      };
    }
  };
  assert.ok(seedPolicies(db) > 0);
  assert.ok(seedCourses(db) > 0);
  seedPolicyDemoActivity(db);
  seedDemoActivity(db);
  const employee = db.prepare("SELECT * FROM users WHERE username = ?").get("employee.demo");
  createMatrix(db, () => {}).reconcileAll();
  assert.ok(createPolicyStore(db).assignedStates(employee).length > 0);
  assert.ok(createTrainingStore(db).assignedCourseStates(employee).length > 0);
  assert.ok(postgres.public.one("SELECT COUNT(*) AS n FROM policies").n > 0);
  assert.ok(postgres.public.one("SELECT COUNT(*) AS n FROM training_courses").n > 0);
});
