import path from "node:path";
import { MessageChannel, Worker, receiveMessageOnPort } from "node:worker_threads";
import pg from "pg";

// The existing feature modules use DatabaseSync's synchronous API. Keep that API while
// moving the actual I/O to a worker, so no module can accidentally fall back to a
// per-instance SQLite database on Vercel. PostgreSQL operations remain serialized.
const identityTables = new Set([
  "users", "audit_events", "notifications", "policies", "policy_versions",
  "policy_reviews", "policy_assignments", "policy_acknowledgements",
  "policy_questions", "policy_exceptions", "training_courses", "training_lessons",
  "training_questions", "training_options", "training_assignments",
  "training_role_requirements", "quiz_attempts", "certificates"
]);

function placeholders(sql) {
  let result = "";
  let quote = null;
  let index = 0;
  for (let i = 0; i < sql.length; i += 1) {
    const char = sql[i];
    if (quote) {
      result += char;
      if (char === quote) {
        if (sql[i + 1] === quote) result += sql[++i];
        else quote = null;
      }
    } else if (char === "'" || char === '"') {
      quote = char;
      result += char;
    } else if (char === "?") {
      result += `$${++index}`;
    } else {
      result += char;
    }
  }
  return result;
}

export function translateSql(source, { schema = false, returning = false } = {}) {
  let sql = String(source).trim();
  if (/^PRAGMA\b/i.test(sql)) return "";
  sql = sql.replace(/\bBEGIN IMMEDIATE\b/gi, "BEGIN");
  sql = sql.replace(/\bINSERT OR IGNORE INTO\b/gi, "INSERT INTO");
  const ignoreConflict = /\bINSERT OR IGNORE INTO\b/i.test(source);
  sql = sql.replace(/\bIFNULL\s*\(/gi, "COALESCE(");
  sql = sql.replace(/\bdisplay_name COLLATE NOCASE\b/gi, "LOWER(display_name)");
  sql = sql.replace(/\busername COLLATE NOCASE\b/gi, "LOWER(username)");
  sql = sql.replace(/\bjson_each\(a\.question_ids\) j\b/gi, "jsonb_array_elements_text(a.question_ids::jsonb) AS j(value)");
  sql = sql.replace(/\bj\.value\b/gi, "j.value::integer");
  sql = sql.replace(/\bversion_label GLOB '\[0-9\]\*\.\[0-9\]\*'/gi, () => "version_label ~ '^[0-9]+\\.[0-9]+$'");
  sql = sql.replace(/\bcurrent_version_id INTEGER REFERENCES policy_versions\(id\) ON DELETE SET NULL/gi, "current_version_id INTEGER");
  sql = sql.replace(/\bCAST\(a\.target_value AS INTEGER\)/gi, "CASE WHEN a.target_type = 'user' THEN a.target_value::integer END");
  sql = sql.replace(/\? IS NULL/gi, "CAST(? AS TEXT) IS NULL");
  if (schema) {
    sql = sql.replace(/\bid INTEGER PRIMARY KEY\b/gi, "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
    const tables = [...sql.matchAll(/CREATE TABLE IF NOT EXISTS\s+([a-z_][a-z_0-9]*)/gi)].map((match) => match[1]);
    if (tables.length) {
      sql += "\n" + tables.map((table) => `ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY; REVOKE ALL ON ${table} FROM anon, authenticated;`).join("\n");
    }
  }
  if (ignoreConflict) sql = `${sql.replace(/;\s*$/, "")} ON CONFLICT DO NOTHING`;
  if (returning) {
    const table = sql.match(/^INSERT INTO\s+([a-z_][a-z_0-9]*)\b/i)?.[1]?.toLowerCase();
    if (identityTables.has(table) && !/\bRETURNING\b/i.test(sql)) sql = `${sql.replace(/;\s*$/, "")} RETURNING id`;
  }
  return placeholders(sql);
}

export class PostgresSync {
  #port;
  #worker;
  #nextId = 0;

  constructor() {
    if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required for PostgreSQL");
    if (!pg.Client) throw new Error("PostgreSQL driver is unavailable");
    const { port1, port2 } = new MessageChannel();
    this.#port = port1;
    this.#worker = new Worker(path.join(process.cwd(), "server", "db", "postgres-worker.js"), {
      workerData: { port: port2 }, transferList: [port2], execArgv: []
    });
    this.#worker.on("error", (error) => console.error("PostgreSQL worker failed", error));
    this.#worker.unref();
    this.#port.unref();
  }

  #request(operation, sql, values = []) {
    const state = new Int32Array(new SharedArrayBuffer(4));
    const id = ++this.#nextId;
    this.#port.postMessage({ id, operation, sql, values, state });
    if (Atomics.wait(state, 0, 0, 25_000) === "timed-out") {
      throw new Error("PostgreSQL request timed out; check DATABASE_URL and network access");
    }
    const response = receiveMessageOnPort(this.#port)?.message;
    if (!response || response.id !== id) throw new Error("PostgreSQL worker returned an invalid response");
    if (response.error) throw new Error(`PostgreSQL: ${response.error}`);
    return response.result;
  }

  exec(source) {
    const schema = /CREATE TABLE IF NOT EXISTS/i.test(source);
    const sql = translateSql(source, { schema });
    if (sql) this.#request("exec", sql);
  }

  prepare(source) {
    const sql = translateSql(source, { returning: true });
    return {
      get: (...values) => this.#request("query", sql, values).rows[0],
      all: (...values) => this.#request("query", sql, values).rows,
      run: (...values) => {
        const result = this.#request("query", sql, values);
        return { changes: result.rowCount, lastInsertRowid: result.rows[0]?.id ?? 0 };
      }
    };
  }
}
